---
- name: Download Golang binary distribution
  get_url:
      url=https://storage.googleapis.com/golang/{{ go_archive_file }}
      dest={{ home }}/{{ go_archive_file }}
- name: Create /home/vagrant/opt folder
  file:
      path=/home/vagrant/opt
      state=directory
- name: Unpack the Go binary distribution
  unarchive:
      copy=no
      src={{ home }}/{{ go_archive_file }}
      dest=/home/vagrant/opt
      creates=/home/vagrant/opt/go
- name: Add go path settings in .bashrc_mods
  lineinfile: dest={{ home }}/.bashrc_mods line="{{ item }}" insertafter=EOF
  with_items:
    - 'export GOROOT={{ go_root }}'
    - 'export GOPATH={{ go_path }}'
    - 'export PATH={{ go_root }}/bin:$PATH'
    - 'export PATH={{ go_path }}/bin:$PATH'
- name: Create go code folder
  file:
    dest={{ go_path }}/src/github.com
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
- name: Install some nice go packages
  command: >
      go get -u {{ item }}
  environment:
      GOPATH: "{{ go_path }}"
      GOROOT: "{{ go_root }}"
      PATH: "{{ go_root }}/bin:{{ go_path }}/bin:/usr/bin:/bin"
  with_items:
      - github.com/nsf/gocode
      - bitbucket.org/gotamer/gowatch