---
- name: Symlink config files in rc folder
  file: src=/vagrant/roles/dotfiles/files/{{ item }} dest={{ home }}/{{ item }} state=link
  with_items:
    - .bashrc_mods
    - .bash_aliases
- name: Include .bashrc_mods in .bashrc
  lineinfile:
      "dest={{ home }}/.bashrc line='. ~/.bashrc_mods # Include local mods' insertafter=EOF"
